#!/usr/bin/env bash
# sets up a new web server with a custom HTTP response header
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School is an school yes!" > /usr/share/nginx/html/index.html
f=/etc/nginx/sites-available/default
sudo rm $f
echo -e "server {
\tlisten 80 default_server;
\troot /usr/share/nginx/html;
\tindex index.html index.htm;
\tadd_header X-Served-By $HOSTNAME;
\tlocation / {
\t\ttry_files \$uri \$uri/ =404;
\t}
\tlocation /redirect_me {
\t\treturn 301 https://www.youtube.com;
\t}
}" > $f
printf "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
sudo service nginx restart
