#!/usr/bin/env bash
# configures a new server with HAproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get install -y haproxy
f=/etc/haproxy/haproxy.cfg
echo -e "
listen
\t
" >> $f
