#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely
trap inv SIGTERM

inv()
{
    echo "I am invincible!!!"
}

while true; do
    echo "To infinity and beyond"
    sleep 2
done
