#!/usr/bin/env bash
# This script gives information about the holbertonschool file
if [ -e "holbertonschool" ]; then
    echo "holbertonschool file exists"
    if [ -s "holbertonschool" ]; then
	echo "holbertonschool is not empty"
    else
	echo "holbertonschool is empty"
    fi
    if [ -f "holbertonschool" ]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi


     
