#!/usr/bin/env bash
# This script transfers a file to a server with usage
# 0-transfer_file FILE_PATH IP USERNAME SSH_PATH
if [ "$#" -lt 3]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi

