#!/usr/bin/env bash
# this script configures a new NGINX server to return a page containing
# the text "Holberton School"
sudo apt-get update -y
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
sudo echo "Holberton School" > /usr/share/nginx/html/index/html
sudo service nginx restart
