#!/usr/bin/env bash
# this script configures a new NGINX server to return a page containing
# the text "Holberton School"
sudo apt-get update -y
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index/html
sudo nginx -s reload
