#!/usr/bin/env bash
# configures a new nginx server with a redirection and 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo /etc/init.d/nginx start
var="rewrite ^/redirect_me$ https://www.youtube.com/ permanent;\n\ttry_files $uri $uri/ =404;\n"
sed -i 's/try_files $uri $uri/ =404;\n/$var' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html
fof="error_page 404 /404.html;\nlocation /404.html {\n\tinternal;\n}\n"
sed -i 's|#error_page 404 /404.html;\n|$fof' /etc/nginx/sites-available/default
sudo nginx -s reload
